version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/streamlit-calculator
    overwrite: yes
permissions:
  - object: /home/ec2-user/streamlit-calculator
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
